<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Evaluate</name>
   <tag></tag>
   <elementGuidId>68a45d41-116d-4f56-b378-66139a8da8cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='__BVID__70']/tbody/tr/td[4]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9af9c2a-849b-4ef4-8527-897713bb15d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-success</value>
      <webElementGuid>9e4a9252-10fe-43c9-bd84-8f7224bea8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Evaluate</value>
      <webElementGuid>3fee3db5-a15b-494d-817d-566eafd18195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__70&quot;)/tbody[1]/tr[1]/td[4]/div[@class=&quot;d-inline-flex align-items-center pt-2&quot;]/button[@class=&quot;btn btn-sm btn-success&quot;]</value>
      <webElementGuid>d7261fa8-d995-4a1a-bb12-409113f9dd79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__70']/tbody/tr/td[4]/div/button</value>
      <webElementGuid>9153933f-64b0-44d5-8a8e-44c06952fa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arpriansah Yonathan'])[1]/following::button[1]</value>
      <webElementGuid>62e06bc4-dae6-434b-bb86-3f2759c1d682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Click to clear sorting)'])[1]/following::button[1]</value>
      <webElementGuid>4b7e98ba-c2df-419f-8444-72d40eba1c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[1]/preceding::button[1]</value>
      <webElementGuid>d72d8163-ffc1-4a89-82a3-2299cddbff5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::button[1]</value>
      <webElementGuid>6cbb0067-88b8-40af-8b9d-4d2f2869f33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Evaluate']/parent::*</value>
      <webElementGuid>c6a62820-7f31-4725-8f2a-0441f35e4fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/button</value>
      <webElementGuid>95a8817f-8906-43cf-a59f-9635f5bbcb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Evaluate' or . = 'Evaluate')]</value>
      <webElementGuid>deab144c-5f34-4ae2-b244-e652596d9801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
