<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TestingTesting 1 flowPMB StikomDemo _2e1fa3</name>
   <tag></tag>
   <elementGuidId>db84bc47-f0db-4320-bd5e-7ec6410259c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dd-event']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-event</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17f2c421-93c1-49fc-aa5d-6ee930de2dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-event</value>
      <webElementGuid>6fe05f78-959b-42a1-9070-361a473b607f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>29d43a4d-4b4e-4e85-83c1-e7cb43e573db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e716d78c-ceb6-47a6-a195-4a38c42d2062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1</value>
      <webElementGuid>2485bff4-39b3-4920-a31f-621eb5af8396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-event&quot;)</value>
      <webElementGuid>d4622663-4879-48b3-8c62-4b5311617998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dd-event']</value>
      <webElementGuid>6ef78fcf-a620-4e0e-8fc1-5b9f8e265fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[3]/div/div/div/div[2]/form/div/div/div/select</value>
      <webElementGuid>c1fa3d65-e9b9-4367-b1d2-f0da25986cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[1]</value>
      <webElementGuid>cecb90c5-a3dc-4813-b19d-7e47798b6d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Notes : ', '&quot;', 'For the final Trust Score please check on Candidate menu', '&quot;', '')])[1]/following::select[1]</value>
      <webElementGuid>abfd5011-ab04-402c-b269-cbf78ca9b511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/preceding::select[1]</value>
      <webElementGuid>4b10af65-cdd4-451a-8970-cbfc382a64dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[2]</value>
      <webElementGuid>eefefe63-852f-4d77-9ef5-f865cc21ecee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c09a0e9f-9094-4809-b61b-88f3e4a7004f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dd-event' and (text() = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1' or . = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1')]</value>
      <webElementGuid>405c0d3c-4f5b-4b3a-b86e-c80e4bb90b33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
