<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TestingTesting 1 flowPMB StikomDemo _2e1fa3</name>
   <tag></tag>
   <elementGuidId>d9787790-a218-4a98-816a-23fc412abf67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dd-event']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-event</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5cfc8567-31ff-45dd-a0d3-049773523cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-event</value>
      <webElementGuid>6407ad10-1554-4cf6-863a-6841834739a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>423e2fdc-180d-41b3-88b9-1a45a869ac6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ac1de5a-6bb3-4bf6-baa4-093802a28cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1</value>
      <webElementGuid>0efc89c3-ca4c-4f75-be0f-764ee5611918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-event&quot;)</value>
      <webElementGuid>209ce2e3-7a60-4522-9d5c-8c5bb2350053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dd-event']</value>
      <webElementGuid>0ddf3255-7efc-45c0-a4bb-9ffba20d752b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div[2]/form/div/div/div/select</value>
      <webElementGuid>97c3282a-2fc4-45e4-9992-5bf211d1a656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[1]</value>
      <webElementGuid>a24b8c3c-94b5-4371-8ca1-d81888673a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::select[1]</value>
      <webElementGuid>b696b9cf-1bcf-4246-9029-f733a55062c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/preceding::select[1]</value>
      <webElementGuid>511509ac-466b-4a92-86b3-2516be37a3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[2]</value>
      <webElementGuid>98401284-635e-4b33-8852-1f1a6a8395c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7efe368d-ad80-4ffd-b840-d190ad17fb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dd-event' and (text() = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1' or . = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1')]</value>
      <webElementGuid>6081ab33-445a-40f0-b75e-37a5d5a9eef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
