<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TestingTesting 1 flowPMB StikomDemo _2e1fa3</name>
   <tag></tag>
   <elementGuidId>2dc970cf-4668-4400-89ea-22fa9a1639cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dd-event']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-event</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>65648b59-f24b-4a75-97bd-27faceab4861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-event</value>
      <webElementGuid>5d5f0f08-a8bf-4944-9780-ebd7f1ec39c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>93090d75-97f4-400e-9e5c-c3fcbb2a4464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3bf302b-e4c0-4729-ba63-5a772a6891c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1</value>
      <webElementGuid>2e428969-a60c-47eb-99ab-55867e2eaa8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-event&quot;)</value>
      <webElementGuid>5c87b97c-736e-4950-a389-77462f2173f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dd-event']</value>
      <webElementGuid>15e2b7d3-03f3-4792-934c-6437305088a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/div[2]/form/div/div/div/select</value>
      <webElementGuid>ff4d8a98-cd86-4ddb-9061-4e92ae1bd627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[1]</value>
      <webElementGuid>4edf2c68-ea69-46c8-be1c-495027e93ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[2]/following::select[1]</value>
      <webElementGuid>9dafeca6-4cd4-4537-a120-c52d10d83542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/preceding::select[1]</value>
      <webElementGuid>1cda314a-9fcd-454f-a9c2-b4c1eeaf2008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[2]</value>
      <webElementGuid>7f61d49a-df3d-4fdf-aa73-4d66c073f47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ec3afc29-fc86-433c-871a-7588ece0759a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dd-event' and (text() = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1' or . = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1')]</value>
      <webElementGuid>94fc6787-749b-476d-8794-665f16af0df4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
