<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Jadwal testing 1 durationJadwal test_0effb2</name>
   <tag></tag>
   <elementGuidId>cbfab187-d656-4f3e-ada5-f208ed77f546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dd-schedule']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-schedule</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>14cbed92-08a0-4f06-ac79-1419e3a26960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-schedule</value>
      <webElementGuid>6099828c-d029-40fd-b5c8-f215cedb1a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>302c7465-819c-400a-8577-a9889adb0e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3924ca4-7342-4807-abd0-9276a1a56069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jadwal testing 1 durationJadwal testing 1 flow expired time</value>
      <webElementGuid>583293f6-d5f8-43fe-9541-82e587573845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-schedule&quot;)</value>
      <webElementGuid>a8ff4159-b6f1-481e-9a2c-6efdfe8b19d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dd-schedule']</value>
      <webElementGuid>6df193ce-6b55-48a8-a408-d9fb23d075ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/div[2]/form/div/div/div[2]/select</value>
      <webElementGuid>7111f940-d6cb-4c9a-89a0-2f419929c4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/following::select[1]</value>
      <webElementGuid>d7cd41d5-4f7b-4815-94cd-20ab446000d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[2]</value>
      <webElementGuid>2aa1965f-c4d1-4061-8f54-aeed5840d927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[1]</value>
      <webElementGuid>cb3f9572-252d-43c5-80e4-dd15b3081106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>37a6b61d-6ad5-4b8b-97bd-9de35119ca19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dd-schedule' and (text() = 'Jadwal testing 1 durationJadwal testing 1 flow expired time' or . = 'Jadwal testing 1 durationJadwal testing 1 flow expired time')]</value>
      <webElementGuid>c1d90cce-d031-4706-8399-91790da83bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
