<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>8081c6f4-661c-488d-9f33-120076c2d55a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='62fafba2906cda3cfaf8b9f5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b8e907b-7397-41a3-ba24-c90ef612ccf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>718ed011-7f6e-4781-b3d4-5e6cdd7dacb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62fafba2906cda3cfaf8b9f5</value>
      <webElementGuid>86e0a9d3-ee91-48de-913c-486a00058113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__45&quot;)/tbody[1]/tr[8]/td[1]/div[@class=&quot;d-inline-flex align-items-center pt-4&quot;]/input[1]</value>
      <webElementGuid>bb609026-c524-4a9e-86b7-b3d1ac25592b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ff51265-6d2a-4f63-84db-ed39fff4797f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>526e066d-9ba2-4a4b-bc56-9b581785a48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62faf8bf906cda3cfaf8b9e7</value>
      <webElementGuid>5d38a697-11b6-4f73-9986-515b4cb506bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__118&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;d-inline-flex align-items-center pt-4&quot;]/input[1]</value>
      <webElementGuid>357fa156-18ed-4a02-a3e5-c68680e60785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='62fafba2906cda3cfaf8b9f5']</value>
      <webElementGuid>f1e5f855-8c29-472a-9931-92a62a2e2e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__45']/tbody/tr[8]/td/div/input</value>
      <webElementGuid>396380c2-fcd9-4e45-96b7-b5d99b4cc0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/input</value>
      <webElementGuid>416c7367-9733-475e-b3ca-a56a9cd3a13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>e8a514a6-bed0-4a11-94b9-7e174626f508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='62faf8bf906cda3cfaf8b9e7']</value>
      <webElementGuid>38d4fec2-9c21-49a9-a03a-f5244c312f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__118']/tbody/tr/td/div/input</value>
      <webElementGuid>528a9e2a-6007-4de3-a981-8795ad321f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4dcd9c99-9650-4e4c-ad06-24f6aae7c1ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
