<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Cancel</name>
   <tag></tag>
   <elementGuidId>f5e9e25e-9184-453a-b7b0-e83c8b180d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/div/div[2]/div[2]/div/div/button/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.text-primary.pr-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>b9296652-3ed8-4bda-936c-f6878500d4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary pr-5</value>
      <webElementGuid>bdb59019-8e25-448d-92f6-edd1da75a88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel </value>
      <webElementGuid>5103d622-eb0d-4a0a-af0b-91d4b11ff906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;main-container-fluid&quot;]/div[@class=&quot;ml-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row pl-5 mt-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row mt-5&quot;]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;span-select borderless&quot;]/h4[@class=&quot;text-primary pr-5&quot;]</value>
      <webElementGuid>056ce7b8-175a-4f2a-aba6-dab6731fed57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/div/div[2]/div[2]/div/div/button/h4</value>
      <webElementGuid>08d9a1d6-389f-4924-96fe-4d09cc172f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to Evaluation'])[1]/following::h4[1]</value>
      <webElementGuid>a39acf20-790b-4c86-9efc-e947d9ca330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movements'])[1]/following::h4[2]</value>
      <webElementGuid>668e9684-29f4-40a5-a3e9-bf3ff67cb931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluated'])[1]/preceding::h4[1]</value>
      <webElementGuid>61c202e0-5989-4eba-858b-6eb1aac8dd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movement Detection'])[1]/preceding::h4[1]</value>
      <webElementGuid>4c83a68a-89b4-44c9-8ac1-c6fafe1c307b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>bf97a65e-2d2d-498f-bb97-bba21ac8ce08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/h4</value>
      <webElementGuid>2180ab70-8291-4e29-8802-12bdbc92d82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' Cancel ' or . = ' Cancel ')]</value>
      <webElementGuid>f07fe7e2-3421-4569-bdad-be3b48dacba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
