<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TestingTesting 1 flowPMB StikomDemo _2e1fa3</name>
   <tag></tag>
   <elementGuidId>b6365d05-60ad-46e5-aad9-bd2286d11bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dd-event']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-event</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09fb96ca-6a63-4e5c-911c-c31398b39d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-event</value>
      <webElementGuid>f21ca946-d245-45b5-a39e-eb26f137664c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>650a7367-07a9-4cba-8768-6dcc5db24efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2b2983f2-7600-4b80-ae76-62cb7a4ea064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1</value>
      <webElementGuid>8f1f4dfd-0b1d-434e-bf7e-7bda1a998065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-event&quot;)</value>
      <webElementGuid>852a0077-ee40-4b7f-b0d0-09f685a92346</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dd-event']</value>
      <webElementGuid>ebcadaf7-5640-4b40-97f9-14744e36961e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/div[2]/form/div/div/div/select</value>
      <webElementGuid>204d79f6-6df8-421f-b3e3-1dbbfea66dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[1]</value>
      <webElementGuid>924534a2-358e-4a71-a588-aead5c810aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidates'])[1]/following::select[1]</value>
      <webElementGuid>49505168-4b87-42e9-ab90-544c17d2a513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/preceding::select[1]</value>
      <webElementGuid>c73e00bb-7f0f-47c8-a266-c057e92543ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[2]</value>
      <webElementGuid>6c5ab298-33d9-4749-9a0c-3d1e3fa92ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>107536bc-1e66-4388-ae88-ba291641373e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dd-event' and (text() = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1' or . = 'TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1')]</value>
      <webElementGuid>7cefdc78-35c8-4be1-bf50-e4369f4f7514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
