<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>1a40abfd-681c-4443-a233-cbba80d364e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='62e88d507b998fcce1a5cd5c']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7360de1c-4aa2-45fd-aaaf-9136627dd959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>feb50d88-55cf-4536-b1b2-f4178003143a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62e88d507b998fcce1a5cd5c</value>
      <webElementGuid>704bc583-7892-4920-ae47-26d47bb283af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__148&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;d-inline-flex align-items-center pt-4&quot;]/input[1]</value>
      <webElementGuid>ff35cf97-0308-4735-8600-ba75a76b5683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>937afc7f-7627-40ce-a96d-76234511d48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a7d5ba3d-1d33-4d31-b8b5-32bb1d1e7af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>62feb60958cdd94b8e7260d2</value>
      <webElementGuid>d25ea507-4d44-4632-999b-841a220a41cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__144&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;d-inline-flex align-items-center pt-4&quot;]/input[1]</value>
      <webElementGuid>dcdb1e00-2c1e-4de0-8cbd-c6b4de71db3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='62e88d507b998fcce1a5cd5c']</value>
      <webElementGuid>0642bab9-f5d1-468a-908a-c6327bcad46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__148']/tbody/tr/td/div/input</value>
      <webElementGuid>cb18f00e-7d0f-424c-9ceb-75b4c9bb19b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>dff913d4-e0ee-4399-8845-d8bf359e2092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>39394122-309e-4ca5-ad1e-f5d64079e625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='62feb60958cdd94b8e7260d2']</value>
      <webElementGuid>332d67c9-7657-4248-aa70-72f8dadbfcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__144']/tbody/tr/td/div/input</value>
      <webElementGuid>3ae17773-2943-44c4-a506-868d42655993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
