<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select Event Name--TestingTesting _1e444c</name>
   <tag></tag>
   <elementGuidId>d117a4ff-21e9-4e0c-bd83-a8487af8bd48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='__BVID__79']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__BVID__79</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>26a0eba2-405b-437f-b1d1-dc341e19d9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>291ca70b-4561-4eb7-b348-327f396d8d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__79</value>
      <webElementGuid>a403d6e6-c148-4b11-b5ba-5745b14fde64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Event Name--TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1</value>
      <webElementGuid>44c3f47f-d3f5-416a-8194-e7f31c29daab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__79&quot;)</value>
      <webElementGuid>de901730-ae70-49d8-acac-08dfa4c95c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='__BVID__79']</value>
      <webElementGuid>25250d38-685a-43c3-8a6a-10f5fbbf2f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/form/div/div/select</value>
      <webElementGuid>781e5b4f-2511-4e71-8de0-74ae705d3466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Name'])[1]/following::select[1]</value>
      <webElementGuid>ad4e9f20-257d-4a51-b9b0-31c492243b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/following::select[1]</value>
      <webElementGuid>6ee5ff94-5e51-4a11-b554-69933a2780d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/preceding::select[1]</value>
      <webElementGuid>c79ede31-a6aa-4e8e-a5cb-7eae23cef035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Name'])[1]/preceding::select[2]</value>
      <webElementGuid>be83e051-4cce-411e-8ea1-1c2835b81174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>484c2bdb-bfde-412f-82c0-00197169b6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '__BVID__79' and (text() = '--Select Event Name--TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1' or . = '--Select Event Name--TestingTesting 1 flowPMB StikomDemo LSPDemo Soca 1Demo SocaContohEVENT BARUAsesmen Public Speaking - Batch 25ujian-1')]</value>
      <webElementGuid>647fe6a3-6712-4a49-8171-fc1600a4c108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
