<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Jadwal testing 1 durationJadwal test_0effb2</name>
   <tag></tag>
   <elementGuidId>75e9f3be-eb88-46b2-a2a5-22c694ad4715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dd-schedule']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dd-schedule</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba7a43c5-ffb7-4f60-b516-9f8bdbed0c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dd-schedule</value>
      <webElementGuid>776c467a-28c4-405d-b3ce-70670f054c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5f99a5e5-9180-4b66-9a0f-a8af1a922427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f10647e2-be64-4449-9bad-adc3b1502842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jadwal testing 1 durationJadwal testing 1 flow expired time</value>
      <webElementGuid>1224686c-4559-4aba-af78-8f02cb7c2165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dd-schedule&quot;)</value>
      <webElementGuid>d5ecc03a-46a5-45e2-8851-fea43ee4c046</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dd-schedule']</value>
      <webElementGuid>5362ba1c-e93b-4e38-8c41-f31c2c77447a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div[2]/div/div/div/div[2]/form/div/div/div[2]/select</value>
      <webElementGuid>982963ec-f0ec-4968-b1c3-acb7b6ef6d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[2]/following::select[1]</value>
      <webElementGuid>19af1ef4-aef3-486f-a44b-2ecfc79e3cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event'])[1]/following::select[2]</value>
      <webElementGuid>a9400886-811f-4911-9e13-fb4577262de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/preceding::select[1]</value>
      <webElementGuid>cd77d649-40c5-41ce-8199-b614780899f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>12f8fd07-43b2-4f49-9ac3-74f217941e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dd-schedule' and (text() = 'Jadwal testing 1 durationJadwal testing 1 flow expired time' or . = 'Jadwal testing 1 durationJadwal testing 1 flow expired time')]</value>
      <webElementGuid>4b4d4d4f-0d6e-4328-876d-52d91ac0b6b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
