<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_18</name>
   <tag></tag>
   <elementGuidId>2aa5b1b5-3427-4cf2-80ea-bddf5d889ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__BVID__84__cell-2000-08-18_']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.btn.border-0.rounded-circle.text-nowrap.focus.active.btn-primary.font-weight-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2cce2610-3168-446e-86b3-f1337806075c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-0 rounded-circle text-nowrap focus active btn-primary font-weight-bold</value>
      <webElementGuid>67a8702f-de7d-4061-b0be-fa6ab18fb662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>606b560e-fd45-4d2f-a2bd-e8408a5f4b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__84__cell-2000-08-18_&quot;)/span[@class=&quot;btn border-0 rounded-circle text-nowrap focus active btn-primary font-weight-bold&quot;]</value>
      <webElementGuid>a232dbb0-d037-45e4-a85e-110c9d97d00c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__84__cell-2000-08-18_']/span</value>
      <webElementGuid>0b733b34-2b1f-454f-a881-f4aa30c9fcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[20]</value>
      <webElementGuid>e126fb30-a73e-461a-8b96-90b156438588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[20]</value>
      <webElementGuid>ee693764-db8b-432c-baa9-63fc1f9be7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cursor keys to navigate calendar dates'])[1]/preceding::span[16]</value>
      <webElementGuid>856c54bc-31f2-4711-ad04-0a6f91973bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friday, August 18, 2000'])[2]/preceding::span[16]</value>
      <webElementGuid>b7e1333a-11b8-45c2-8b5c-929b0dc09197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='18']/parent::*</value>
      <webElementGuid>843f21cb-b81c-4de9-a406-ae985ab2f1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[6]/span</value>
      <webElementGuid>17d3d9ef-a7aa-4105-8089-676155faac6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '18' or . = '18')]</value>
      <webElementGuid>5736f2f5-8125-445f-bea2-6447e403d203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
