<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Jadwal testing1_btn btn-danger</name>
   <tag></tag>
   <elementGuidId>898127d5-5d90-4933-af3c-2227fa5e9bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='__BVID__82']/tbody/tr/td[6]/div/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b60fabb-f68c-4f74-b8cb-48bd37afd5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>086c6bca-6ac1-4617-8f63-db378196bb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__82&quot;)/tbody[1]/tr[1]/td[6]/div[@class=&quot;d-inline-flex align-items-center&quot;]/button[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>464313e3-d69b-4e66-93c0-37b50a2f500d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f65632b6-5cb0-4f31-82d5-4f2d771f071f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger</value>
      <webElementGuid>fb9a833b-3762-450d-9e77-2e9c7e4c15aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__82&quot;)/tbody[1]/tr[1]/td[6]/div[@class=&quot;d-inline-flex align-items-center&quot;]/button[@class=&quot;btn btn-danger&quot;]</value>
      <webElementGuid>baf42ff4-282a-4273-9605-51df6b4a2332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='__BVID__82']/tbody/tr/td[6]/div/button[3]</value>
      <webElementGuid>783ca8bb-db34-4cf5-bd29-613f63fa9d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jadwal testing1'])[1]/following::button[3]</value>
      <webElementGuid>a229fd13-9e5c-443c-ba23-6619803a3af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes'])[1]/following::button[3]</value>
      <webElementGuid>60ef4c54-da34-4053-98ee-9ce5be3cb6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing'])[1]/preceding::button[1]</value>
      <webElementGuid>8854ec05-463d-4934-8aad-974759c6204e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing'])[1]/preceding::button[1]</value>
      <webElementGuid>1b18efc2-f1a5-4d4f-9927-9733d7355288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>b345cd0f-304a-452b-a678-70e1fb1871e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing'])[1]/following::button[3]</value>
      <webElementGuid>5adb6e1d-3dd9-461c-865a-cdad00962a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing 1 flow'])[1]/preceding::button[1]</value>
      <webElementGuid>9ce001de-edcd-413e-b174-3b77476aa941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qwerty'])[1]/preceding::button[1]</value>
      <webElementGuid>5f4fbe1f-4646-4f3a-9f55-60f3dc617cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
